# Generated by Django 3.2 on 2026-05-07 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260507_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gatelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='class_designation',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='is_staff_member',
            field=models.BooleanField(default=True),
        ),
        migrations.RenameModel(
            old_name='UserType',
            new_name='MemberType',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membertype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='circulation',
            name='member',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatelog',
            name='member',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.member'),
            preserve_default=False,
        ),
    ]
